-- Drop all tables first to ensure a clean start
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE SCHEDULE CASCADE CONSTRAINTS;
DROP TABLE DEPT_LOCATION CASCADE CONSTRAINTS;
DROP TABLE TAKES CASCADE CONSTRAINTS;
DROP TABLE DEPARTMENT_EVENT CASCADE CONSTRAINTS;
DROP TABLE ACADEMIC_EVENT CASCADE CONSTRAINTS;
DROP TABLE SECTION CASCADE CONSTRAINTS;
DROP TABLE COURSE CASCADE CONSTRAINTS;
DROP TABLE STUDENT_GROUP CASCADE CONSTRAINTS; -- 이름 변경: GROUP -> STUDENT_GROUP
DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;
DROP TABLE STUDENT CASCADE CONSTRAINTS;
DROP TABLE FRIENDSHIP CASCADE CONSTRAINTS;

-- Create Tables
CREATE TABLE STUDENT (
    STUDENT_ID CHAR(10) PRIMARY KEY,
    NAME       VARCHAR2(30) NOT NULL,
    DEPT_ID    VARCHAR2(4) NOT NULL
);

CREATE TABLE DEPARTMENT (
    DEPT_ID   VARCHAR2(4) PRIMARY KEY,
    DEPT_NAME VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE COURSE (
    COURSE_ID VARCHAR2(20) NOT NULL,   -- 강좌번호 (예: COMP0320)
    TITLE     VARCHAR2(100) NOT NULL,   -- 교과목명 (길이 증가)
    CREDITS   NUMBER(2) NOT NULL,   -- 학점 (INT -> NUMBER)
    PRIMARY KEY ( COURSE_ID )
);

CREATE TABLE SECTION (
    SECTION_ID    VARCHAR2(30) NOT NULL,
    ACADEMIC_TERM NUMBER(6) NOT NULL,   -- 학기 (INT -> NUMBER, 예: 202501)
    COURSE_ID     VARCHAR2(20) NOT NULL,
    TIME          VARCHAR2(150),
    LOCATION      VARCHAR2(150),
    PRIMARY KEY ( SECTION_ID,
                  COURSE_ID )
);

CREATE TABLE TAKES (
    STUDENT_ID CHAR(10) NOT NULL,   -- STUDENT를 참조하는 FK
    COURSE_ID  VARCHAR2(20) NOT NULL,   -- SECTION을 참조하는 (복합) FK의 일부
    SECTION_ID VARCHAR2(30) NOT NULL,   -- SECTION을 참조하는 (복합) FK의 일부
	-- "어떤 학생이", "어떤 과목의", "어떤 분반"을 수강했는가는 유일해야 함
    PRIMARY KEY ( STUDENT_ID,
                  COURSE_ID,
                  SECTION_ID )
);

CREATE TABLE ACADEMIC_EVENT (
    ACADEMIC_EVENT_ID NUMBER NOT NULL,
    TITLE             VARCHAR2(200) NOT NULL,
    START_DATE        DATE NOT NULL,
    END_DATE          DATE,
    PRIMARY KEY ( ACADEMIC_EVENT_ID )
);

CREATE TABLE DEPARTMENT_EVENT (
    DEPARTMENT_ID VARCHAR2(4) NOT NULL,	--DEPARTMENT relation의 Dept_id 외래키
    DEPT_EVENT_ID NUMBER NOT NULL,
    TITLE         VARCHAR2(200) NOT NULL,
    START_DATE    DATE NOT NULL,
    END_DATE      DATE NOT NULL,
    PRIMARY KEY ( DEPT_EVENT_ID )
);

-- ER-Diagram에서 DEPARTMENT_EVENT의 Location Attribute를 DEPT_LOCATION table로 분리
CREATE TABLE DEPT_LOCATION (
    DEPT_EVENT_ID NUMBER NOT NULL,
    LOCATION      VARCHAR2(40) NOT NULL,
    PRIMARY KEY ( DEPT_EVENT_ID,
                  LOCATION )
);

-- 기존 ER-Diagram에서 SCHEDULE 엔티티의 Date Attribute 中 Start_time과 End_time만 사용
-- Category Attribute 보류, 
CREATE TABLE SCHEDULE (
    SCHEDULE_ID NUMBER NOT NULL, -- Primary Key
    TITLE       VARCHAR2(40) NOT NULL,
    START_TIME  TIMESTAMP NOT NULL,
    END_TIME    TIMESTAMP NOT NULL,
    STUDENT_ID  CHAR(10) NOT NULL,	-- Foreign Key
    PRIMARY KEY ( SCHEDULE_ID )
);

-- 기존 ER-Diagram에서 GROUP 엔티티의 Member Attribute를 테이블로 분리
-- Name을 가독성과 참조성을 위해 G_Name으로 변경
CREATE TABLE STUDENT_GROUP (
    GROUP_ID     NUMBER NOT NULL, -- Primary Key
    G_NAME       VARCHAR2(40) NOT NULL,
    PURPOSE      VARCHAR2(30),
    LEADER       CHAR(10) NOT NULL, -- Leaader Column에 STUDENT Table의 Student_id 값을 할당, 
    MEMBER_COUNT NUMBER NOT NULL,
    PRIMARY KEY ( GROUP_ID )
);

-- MEMBER Relation을 통해 GROUP 엔티티와 STUDENT 엔티티간의 Relationship(관계) 생성
CREATE TABLE MEMBER (
    GROUP_ID   NUMBER NOT NULL,	-- Foreign Key
    STUDENT_ID CHAR(10) NOT NULL,
    PRIMARY KEY ( GROUP_ID,
            STUDENT_ID )				-- Composite Primary Key
);

-- ##### FREINDSHIP Relation 추가 #####
CREATE TABLE FRIENDSHIP (
    STUDENT_ID1 CHAR(10) NOT NULL,
    STUDENT_ID2 CHAR(10) NOT NULL,
    PRIMARY KEY ( STUDENT_ID1,
                  STUDENT_ID2 )
);

COMMIT;