-- 외래키 추가 (**INSERT문 이후 추가 해야함)
ALTER TABLE STUDENT
    ADD CONSTRAINT FK_STUDENT_DEPARTMENT FOREIGN KEY ( DEPT_ID )
        REFERENCES DEPARTMENT ( DEPT_ID );
ALTER TABLE SECTION
    ADD CONSTRAINT FK_SECTION_COURSE FOREIGN KEY ( COURSE_ID )
        REFERENCES COURSE ( COURSE_ID ); 
-- STUDENT 테이블 참조 FK
ALTER TABLE TAKES
    ADD CONSTRAINT FK_TAKES_STUDENT
        FOREIGN KEY ( STUDENT_ID )
            REFERENCES STUDENT ( STUDENT_ID )
                ON DELETE CASCADE; -- 학생이 삭제되면 수강신청 내역도 함께 삭제

-- FK가 (Course_id, Section_id) 복합 키를 참조하도록 변경
ALTER TABLE TAKES
    ADD CONSTRAINT FK_TAKES_SECTION
        FOREIGN KEY ( COURSE_ID,
                      SECTION_ID )
            REFERENCES SECTION ( COURSE_ID,
                                 SECTION_ID )
                ON DELETE CASCADE; -- 분반이 삭제되면 수강신청 내역도 함께 삭제
ALTER TABLE DEPARTMENT_EVENT
    ADD CONSTRAINT FK_DEPTEVENT_DEPT FOREIGN KEY ( DEPARTMENT_ID )
        REFERENCES DEPARTMENT ( DEPT_ID );

ALTER TABLE DEPT_LOCATION
    ADD CONSTRAINT FK_DEPTLOC_DEPTEVENT FOREIGN KEY ( DEPT_EVENT_ID )
        REFERENCES DEPARTMENT_EVENT ( DEPT_EVENT_ID );

ALTER TABLE SCHEDULE
    ADD CONSTRAINT FK_SCHEDULE_STUDENT FOREIGN KEY ( STUDENT_ID )
        REFERENCES STUDENT ( STUDENT_ID );

ALTER TABLE STUDENT_GROUP
    ADD CONSTRAINT FK_GROUP_LEADER FOREIGN KEY ( LEADER )
        REFERENCES STUDENT ( STUDENT_ID ); -- GROUP 테이블 리더 FK 추가

ALTER TABLE MEMBER
    ADD CONSTRAINT FK_MEMBER_GROUP FOREIGN KEY ( GROUP_ID )
        REFERENCES STUDENT_GROUP ( GROUP_ID ); -- 참조 테이블 이름 수정

ALTER TABLE MEMBER
    ADD CONSTRAINT FK_MEMBER_STUDENT FOREIGN KEY ( STUDENT_ID )
        REFERENCES STUDENT ( STUDENT_ID ); -- MEMBER 테이블 학생 FK 추가

-- 멤버는 반드시 존재하는 그룹에 속함
ALTER TABLE MEMBER
    ADD CONSTRAINT FK_MEMBER_GROUP FOREIGN KEY ( GROUP_ID )
        REFERENCES STUDENT_GROUP ( GROUP_ID );

-- 멤버는 반드시 존재하는 학생이어야 함
ALTER TABLE MEMBER
    ADD CONSTRAINT FK_MEMBER_STUDENT FOREIGN KEY ( STUDENT_ID )
        REFERENCES STUDENT ( STUDENT_ID );

-- FRIENDSHIP 테이블의 외래키 설정
ALTER TABLE FRIENDSHIP
    ADD CONSTRAINT FK_FRIENDSHIP_STUDENT1
        FOREIGN KEY ( STUDENT_ID1 )
            REFERENCES STUDENT ( STUDENT_ID )
                ON DELETE CASCADE; -- 학생 삭제 시 친구 관계도 삭제

ALTER TABLE FRIENDSHIP
    ADD CONSTRAINT FK_FRIENDSHIP_STUDENT2
        FOREIGN KEY ( STUDENT_ID2 )
            REFERENCES STUDENT ( STUDENT_ID )
                ON DELETE CASCADE;

-- 중복 방지를 위해 ID1이 ID2보다 작도록 강제하는 제약조건
ALTER TABLE FRIENDSHIP ADD CONSTRAINT CHK_FRIENDSHIP_ID_ORDER CHECK ( STUDENT_ID1 < STUDENT_ID2 );
COMMIT;